
services:
  php:
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev
    depends_on:
      - db
      - redis

  node:
    build:
      context: .
      dockerfile: infra/node/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "while true; do sleep 1; done"]

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masteroftickets
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    volumes:
      - ./backend/public:/var/www/html:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  postgres_data: